CREATE SCHEMA IF NOT EXISTS "jpa_utils" ;
  
CREATE TABLE  IF NOT EXISTS  "jpa_utils"."user" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	first_name varchar(255) NULL,
	last_name varchar(255) NULL,
	CONSTRAINT user_pkey PRIMARY KEY (id)
);
 
--- DUMMY PROCEDURE FOR TESTING
CREATE OR REPLACE PROCEDURE "jpa_utils".raise_notice_check()
 LANGUAGE plpgsql
AS $procedure$
BEGIN 

    
    
    RAISE LOG  'Log from procedure...'; --this is not visible in console
    RAISE DEBUG  'DEBUG from procedure..'; -- this is not visible in console
     
    RAISE INFO  'INFO from procedure...'; 
    RAISE WARNING  'WARNING  from procedure...';
    -- this is only visible if  spring.jpa.hibernate.ddl-auto: validate 
    RAISE NOTICE 'Notice from procedure ...'; 
    -- if spring.jpa.hibernate.ddl-auto: create it will not be visible in console 
    
 --   RAISE EXCEPTION  'EXCEPTION  from procedure...'; 
    
END;
$procedure$
$$ 