schema_name: jpa_utils

spring:   
  application:
    name: JpaUtils 
  docker:
    compose:
      enabled: false
  sql:
    init: 
      platform: postgres
      continue-on-error: false
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD} 
      mode: always
      separator: $$
      schema-locations: classpath:db/schema-pg.sql
#      data-locations: db/import_*_users.sql  
  datasource: 
     url: jdbc:postgresql://localhost:5432/oselan
     driver-class-name: org.postgresql.Driver
     username: ${DATASOURCE_USERNAME}
     password: ${DATASOURCE_PASSWORD}  
     hikari:
       maximumPoolSize: ${DATASOURCE_MAX_POOL_SIZE:2}   
  jpa:  
    show-sql: false
    defer-datasource-initialization: false
    open-in-view: false 
    hibernate:
      ddl-auto: validate
    properties:
      hibernate: 
        default_schema: ${schema_name}
        format_sql: false
        physical_naming_strategy: com.oselan.config.SnakeCaseNamingStrategy
        globally_quoted_identifiers: true
    
logging:
  level:
    org.hibernate.type: INFO
    org.hibernate.SQL: debug